### ISSUE TITLE
Design Docs Review 

### ISSUE THREAD

**Issue by jliversi** [lfs48/Euler#1]
Hey Lucas, great job on your docs so far, I just have a few recommendations: 

MVP LIST 

- [x] Potentially consider leaving video and audio posts to a bonus, as these are a lot more difficult to hook up initially
- [x] It seems that feed requires follows, so should that be an earlier MVP? 
- [x] You already have 7 MVPs without reblogs, so go ahead and push that to a bonus. 

SCHEMA 

It looks like you've already implemented my notes from slack. Nice!

SAMPLE STATE 
- [x]  Your sample state looks really good, but the one question I have is what is referenced by "followIds" in the users slice. Are these going to refer to tags or to users? Or, if they refer to general "follows", should we have a slice of state for follows?

**Comment by lfs48** [comment]
Thank you for the feedback Josh! I've made changes to address all your points.
