### ISSUE TITLE
Design Docs Review #2 

### ISSUE THREAD

**Issue by jliversi** [lfs48/Euler#2]
BACKEND ROUTES 

- [x] We don't need a post to tags route as tags will be created on creation/update of posts, so that functionality will live in those routes 
- [x] No need for GET for likes or follows, as we'll only care about associated posts/users, and so don't need separate routes for just grabbing the likes/follows. 
- [x] Change wildcard to :tag_id in follows post/delete (nested under tag)

FRONTEND ROUTES 
- [x] No footer (except as potential bonus, ex. turning off infinite scroll) 
- [x] Look at how similar the signup and login forms are on tumblr. Can they be the same `SessionForm` or do we need separate `LoginForm` and `SignupForm`
- [x] Flesh out postsIndex with a createPost component and SideBar component (with necessary children) (also add necessary notes components to the PostIndexItems)
- [x] Consider how you'll handle routing with createPost and the fact that posts index should still be rendered underneath. (Probably just have /new also render dashboard) 
- [x] Is there a "PostShow" on real tumblr? If not, let's remove this route. If so, let's add the other relevant components.

**Comment by lfs48** [comment]
Thanks for the feedback Josh! I've made changes to address all these points, along with a couple with a couple of other things.
